import { useState, useCallback } from 'react';
import { useWebContainer } from './useWebContainer';
import logger from '@/lib/logger';

export function useFiles(initialSessionId: string = '') {
  const [files, setFiles] = useState<Record<string, string>>({});
  const [activeFile, setActiveFile] = useState<string>('');
  const [sessionId, setSessionId] = useState<string>(initialSessionId);
  const { webcontainer } = useWebContainer();

  // Write a single file to both React state and WebContainer FS
  const updateFile = useCallback(async (path: string, content: string) => {
      const cleanPath = path.startsWith('/') ? path.substring(1) : path;

      // Update local state for UI
      setFiles(prev => ({ ...prev, [cleanPath]: content }));

      // Write directly to WebContainer file system
      if (webcontainer) {
          try {
              const parts = cleanPath.split('/');
              if (parts.length > 1) {
                  const dir = parts.slice(0, -1).join('/');
                  await webcontainer.fs.mkdir(dir, { recursive: true });
              }
              await webcontainer.fs.writeFile(cleanPath, content);
              logger.debug('[useFiles] Wrote file to WebContainer:', cleanPath);
          } catch (err) {
              console.error('[useFiles] Failed to write file to WebContainer:', cleanPath, err);
          }
      }
  }, [webcontainer]);

  // Recursively read all files from WebContainer FS
  const readDirectoryRecursive = useCallback(async (
    dirPath: string,
    result: Record<string, string>
  ): Promise<void> => {
    if (!webcontainer) return;

    try {
      const entries = await webcontainer.fs.readdir(dirPath, { withFileTypes: true });
      for (const entry of entries) {
        const entryPath = dirPath ? `${dirPath}/${entry.name}` : entry.name;

        // Skip node_modules, .git, hidden directories, and system config files
        if (entry.name === 'node_modules' || entry.name === '.git' || entry.name === '.cache') {
          continue;
        }

        // Skip system config files written by useDevServer at the root level
        if (!dirPath && (entry.name === '.npmrc' || entry.name === '.env')) {
          continue;
        }

        // Skip lock files generated by npm install inside WebContainer
        if (entry.name === 'package-lock.json' || entry.name === 'yarn.lock' || entry.name === 'pnpm-lock.yaml') {
          continue;
        }

        if (entry.isDirectory()) {
          await readDirectoryRecursive(entryPath, result);
        } else if (entry.isFile()) {
          try {
            const content = await webcontainer.fs.readFile(entryPath, 'utf-8');
            result[entryPath] = content;
          } catch (readErr) {
            console.warn('[useFiles] Failed to read file:', entryPath, readErr);
          }
        }
      }
    } catch (err) {
      console.error('[useFiles] Failed to read directory:', dirPath, err);
    }
  }, [webcontainer]);

  // Load all files from WebContainer FS (replaces old /api/files backend call)
  const loadAllFiles = useCallback(async (_sessionId?: string) => {
    if (!webcontainer) {
      console.warn('[useFiles] WebContainer not ready, skipping loadAllFiles');
      return;
    }

    logger.debug('[useFiles] Loading all files from WebContainer FS...');
    const fileContents: Record<string, string> = {};
    await readDirectoryRecursive('', fileContents);

    const filePaths = Object.keys(fileContents);
    logger.debug('[useFiles] Loaded', filePaths.length, 'files from WebContainer FS');

    setFiles(fileContents);

    // Auto-select first file if none is active
    if (filePaths.length > 0 && !activeFile) {
      setActiveFile(filePaths[0]);
    }
  }, [webcontainer, readDirectoryRecursive, activeFile]);

  return {
    files,
    setFiles,
    activeFile,
    setActiveFile,
    sessionId,
    setSessionId,
    loadAllFiles,
    updateFile
  };
}
